
"""Render scan reports to various formats."""
from typing import Any
import json

def to_markdown(report: dict[str, Any]) -> str:
    lines = [
        f'# DarkLead Scan Report',
        f'',
        f'**Repository:** {report.get("repo_url", "unknown")}',
        f'**Grade:** {report.get("grade", "?")} | **Score:** {report.get("debt_score", 0)}/100',
        f'**Total Issues:** {report.get("issue_count", 0)}',
        f'',
        f'## Executive Summary',
        f'',
        report.get("summary", "No summary available."),
        f'',
        f'## Findings',
        f'',
        f'| Severity | Rule | Message | File | Line |',
        f'|----------|------|---------|------|------|',
    ]
    for issue in report.get("issues", []):
        lines.append(f'| {issue.get("severity","?")} | `{issue.get("rule","?")}` | {issue.get("message","")[:60]} | {issue.get("file_path","?")[:30]} | {issue.get("line_number","?")} |')
    lines += ['', f'---', f'*Generated by DarkLead AI — {report.get("created_at", "")}*']
    return '\n'.join(lines)

def to_sarif(report: dict[str, Any], tool_name: str='DarkLead') -> dict:
    rules = {}
    results = []
    for issue in report.get('issues', []):
        rule_id = issue.get('rule', 'unknown')
        if rule_id not in rules:
            rules[rule_id] = {'id': rule_id, 'name': rule_id, 'shortDescription': {'text': issue.get('message', '')[:100]}}
        results.append({
            'ruleId': rule_id,
            'level': {'critical':'error','major':'warning','minor':'note','info':'none'}.get(issue.get('severity','info'), 'note'),
            'message': {'text': issue.get('message', '')},
            'locations': [{'physicalLocation': {'artifactLocation': {'uri': issue.get('file_path','')},
                                                'region': {'startLine': issue.get('line_number',1) or 1}}}]
        })
    return {
        'version': '2.1.0',
        '$schema': 'https://json.schemastore.org/sarif-2.1.0.json',
        'runs': [{'tool': {'driver': {'name': tool_name, 'version': '1.0.0', 'rules': list(rules.values())}}, 'results': results}]
    }
